[package]
name = "renamer"
version = "0.2.4" # Also change version in the main.
authors = ["hhandika"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
walkdir = "2.3.1"